### ISSUE TITLE
网站无法正常打开

### ISSUE THREAD

**Issue by xiaozhu2007** [SlimefunGuguProject/Slimefun-Wiki#103]
### 问题描述

网站打开后提示“加载中”
![image](https://github.com/SlimefunGuguProject/Slimefun-Wiki/assets/63779340/216bf4ae-c91a-4f6b-b7d2-6cb6870aed75)

经过调试发现是 unpkg 相关返回了 403 状态码导致无法正常使用
![image](https://github.com/SlimefunGuguProject/Slimefun-Wiki/assets/63779340/1747a948-402c-4a2e-99e3-73b43695db26)

本地替换后可使用

**Comment by ybw0014** [comment]
403通常是因为你的IP访问太频繁，请尝试更换网络或浏览器
