### ISSUE TITLE
无法访问此网站找不到 slimefun-wiki.guizhanss.cn 的服务器 IP 地址。

### ISSUE THREAD

**Issue by charassss** [SlimefunGuguProject/Slimefun-Wiki#126]
### 问题描述

无法访问此网站找不到 slimefun-wiki.guizhanss.cn 的服务器 IP 地址。

![image](https://github.com/user-attachments/assets/f7b3de9a-a850-4271-af8e-6f92c58b7123)

Both wifi, cellular data can't work.

![image](https://github.com/user-attachments/assets/763a632d-8a1b-4dc1-bd4a-8255fc63839b)
![image](https://github.com/user-attachments/assets/b6b7ec54-6463-4309-9284-c1729d8ab247)

**Comment by ybw0014** [comment]
请暂时使用备用地址 https://slimefun-wiki.guizhanss.net/
